import numpy as np
import matplotlib.pyplot as plt
import cv2
from skimage.feature import local_binary_pattern
from skimage.feature import graycomatrix, graycoprops
from scipy.stats import skew
import os

# 设置中文字体支持
plt.rcParams['font.sans-serif'] = ['SimHei', 'Microsoft YaHei', 'DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

# 定义输出目录
OUTPUT_DIR = r"C:\Users\ASUS\Desktop\AI_Recognition\processed_tunnel_face_photos\4"

# 确保输出目录存在
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)
    print(f"已创建目录: {OUTPUT_DIR}")

def conceptual_glcm(image_patch, distance, angle_deg, levels=8):
    """概念性GLCM构建示意
    
    参数:
        image_patch: 输入图像块
        distance: 像素间距离
        angle_deg: 角度（度）
        levels: 灰度级数
    
    返回:
        glcm_normalized: 归一化的GLCM矩阵 p(i,j)
    """
    glcm = np.zeros((levels, levels), dtype=np.float64)
    rows, cols = image_patch.shape

    # 根据角度确定偏移量 (dr, dc)
    if angle_deg == 0:
        dr, dc = 0, distance
    elif angle_deg == 45:
        dr, dc = -distance, distance
    elif angle_deg == 90:
        dr, dc = -distance, 0
    elif angle_deg == 135:
        dr, dc = -distance, -distance
    else:
        raise ValueError("不支持的角度，仅支持0, 45, 90, 135度")

    for r in range(rows):
        for c in range(cols):
            i = image_patch[r, c]
            
            # 计算目标像素位置
            nr, nc = r + dr, c + dc
            
            # 检查边界
            if 0 <= nr < rows and 0 <= nc < cols:
                j = image_patch[nr, nc]
                glcm[i, j] += 1
    
    # 归一化GLCM得到概率 p(i,j)
    if np.sum(glcm) > 0:
        glcm_normalized = glcm / np.sum(glcm)
    else:
        glcm_normalized = glcm
        
    return glcm_normalized

def calculate_glcm_features(glcm_matrix):
    """计算GLCM纹理特征
    
    参数:
        glcm_matrix: GLCM矩阵
    
    返回:
        features: 包含各种纹理特征的字典
    """
    features = {}
    
    # 对比度 (Contrast)
    contrast = 0
    for i in range(glcm_matrix.shape[0]):
        for j in range(glcm_matrix.shape[1]):
            contrast += glcm_matrix[i, j] * (i - j) ** 2
    features['对比度'] = contrast
    
    # 相关性 (Correlation)
    mu_i = np.sum([i * np.sum(glcm_matrix[i, :]) for i in range(glcm_matrix.shape[0])])
    mu_j = np.sum([j * np.sum(glcm_matrix[:, j]) for j in range(glcm_matrix.shape[1])])
    
    sigma_i = np.sqrt(np.sum([(i - mu_i) ** 2 * np.sum(glcm_matrix[i, :]) for i in range(glcm_matrix.shape[0])]))
    sigma_j = np.sqrt(np.sum([(j - mu_j) ** 2 * np.sum(glcm_matrix[:, j]) for j in range(glcm_matrix.shape[1])]))
    
    correlation = 0
    if sigma_i > 0 and sigma_j > 0:
        for i in range(glcm_matrix.shape[0]):
            for j in range(glcm_matrix.shape[1]):
                correlation += ((i - mu_i) * (j - mu_j) * glcm_matrix[i, j]) / (sigma_i * sigma_j)
    features['相关性'] = correlation
    
    # 能量 (Energy/Angular Second Moment)
    energy = np.sum(glcm_matrix ** 2)
    features['能量'] = energy
    
    # 同质性 (Homogeneity)
    homogeneity = 0
    for i in range(glcm_matrix.shape[0]):
        for j in range(glcm_matrix.shape[1]):
            homogeneity += glcm_matrix[i, j] / (1 + abs(i - j))
    features['同质性'] = homogeneity
    
    return features

def plot_glcm(glcm_matrix, title="灰度共生矩阵", features=None):
    """绘制GLCM热力图"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    
    # 绘制GLCM热力图
    cax = ax1.matshow(glcm_matrix, cmap='Blues')
    fig.colorbar(cax, ax=ax1)
    ax1.set_title(f"{title}热力图", fontsize=14, pad=20)
    ax1.set_xlabel("灰度级 j", fontsize=12)
    ax1.set_ylabel("灰度级 i", fontsize=12)
    # 设置坐标轴刻度向内
    ax1.tick_params(axis='both', direction='in', which='both')
    
    # 添加数值标注（仅当矩阵较小时）
    if glcm_matrix.shape[0] <= 10 and glcm_matrix.shape[1] <= 10:
        for i in range(glcm_matrix.shape[0]):
            for j in range(glcm_matrix.shape[1]):
                ax1.text(j, i, f"{glcm_matrix[i, j]:.2f}", 
                        va='center', ha='center', color='red', fontsize=8)
    
    # 绘制特征柱状图
    if features:
        feature_names = list(features.keys())
        feature_values = list(features.values())
        
        bars = ax2.bar(feature_names, feature_values, color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'])
        ax2.set_title("GLCM纹理特征", fontsize=14, pad=20)
        ax2.set_ylabel("特征值", fontsize=12)
        ax2.tick_params(axis='x', rotation=45)
        # 设置坐标轴刻度向内
        ax2.tick_params(axis='both', direction='in', which='both')
        
        # 添加数值标签
        for bar, value in zip(bars, feature_values):
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                    f'{value:.3f}', ha='center', va='bottom', fontsize=10)
    
    plt.tight_layout()
    filename = os.path.join(OUTPUT_DIR, title.replace(" ", "_") + ".png")
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"已保存GLCM图表到: {filename}")
    plt.close(fig)

def plot_color_moments(moments, title="颜色矩特征"):
    """绘制颜色矩柱状图"""
    if not moments:
        print("没有颜色矩数据可绘制")
        return

    num_channels = len(moments)
    moment_names = ['均值', '标准差', '偏度']
    bar_width = 0.25
    index = np.arange(len(moment_names))

    fig, ax = plt.subplots(figsize=(12, 8))
    channel_colors = {'蓝色通道': '#1f77b4', '绿色通道': '#2ca02c', '红色通道': '#d62728'}

    for i, (channel_name, channel_moments) in enumerate(moments.items()):
        values = [channel_moments['均值'], channel_moments['标准差'], channel_moments['偏度']]
        bars = ax.bar(index + i * bar_width, values, bar_width, 
                     label=channel_name, color=channel_colors.get(channel_name, 'gray'))
        
        # 添加数值标签
        for bar, value in zip(bars, values):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + max(values) * 0.01,
                   f'{value:.2f}', ha='center', va='bottom', fontsize=9)

    ax.set_xlabel('颜色矩类型', fontsize=12)
    ax.set_ylabel('特征值', fontsize=12)
    ax.set_title(title, fontsize=14, pad=20)
    ax.set_xticks(index + bar_width * (num_channels - 1) / 2)
    ax.set_xticklabels(moment_names)
    ax.legend(fontsize=11)
    ax.grid(True, linestyle='--', alpha=0.7)
    # 设置坐标轴刻度向内
    ax.tick_params(axis='both', direction='in', which='both')
    
    plt.tight_layout()
    filename = os.path.join(OUTPUT_DIR, title.replace(" ", "_") + ".png")
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"已保存颜色矩图表到: {filename}")
    plt.close(fig)

def calculate_color_moments(image_patch):
    """计算颜色矩特征
    
    参数:
        image_patch: 输入的彩色图像块 (H, W, 3)
    
    返回:
        moments: 包含各通道颜色矩的字典
    """
    if image_patch is None or image_patch.size == 0:
        print("输入图像为空")
        return None
        
    # 确保图像是3通道的
    if len(image_patch.shape) != 3 or image_patch.shape[2] != 3:
        print(f"图像形状不正确: {image_patch.shape}, 需要 (H, W, 3)")
        return None
    
    moments = {}
    channel_names = ['蓝色通道', '绿色通道', '红色通道']  # BGR顺序
    
    for i, channel_name in enumerate(channel_names):
        channel_data = image_patch[:, :, i].flatten().astype(np.float64)
        
        # 计算一阶矩（均值）
        mean = np.mean(channel_data)
        
        # 计算二阶矩（标准差）
        std = np.std(channel_data)
        
        # 计算三阶矩（偏度）
        skewness = skew(channel_data)
        
        moments[channel_name] = {
            '均值': mean,
            '标准差': std,
            '偏度': skewness
        }
        
        print(f"{channel_name}: 均值={mean:.2f}, 标准差={std:.2f}, 偏度={skewness:.3f}")
    
    return moments

def calculate_and_plot_lbp(image_patch_gray, P=8, R=1, title_prefix="局部二值模式"):
    """计算LBP并绘制LBP图像和直方图"""
    if image_patch_gray is None or image_patch_gray.size == 0:
        print("错误：输入的灰度图像块为空")
        return
    if image_patch_gray.ndim != 2:
        print(f"错误：LBP输入图像必须是灰度图像，当前维度为 {image_patch_gray.ndim}")
        return

    lbp_image = local_binary_pattern(image_patch_gray, P, R, method='uniform')
    
    # 创建子图
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    
    # 绘制LBP图像
    im = ax1.imshow(lbp_image, cmap='gray')
    ax1.set_title(f"{title_prefix}图像 (P={P}, R={R})", fontsize=14)
    ax1.axis('off')
    fig.colorbar(im, ax=ax1)
    
    # 绘制LBP直方图
    hist, bins = np.histogram(lbp_image.ravel(), bins=np.arange(0, P + 3), range=(0, P + 2))
    bars = ax2.bar(np.arange(0, P + 2), hist, width=0.8, color='#1f77b4', alpha=0.7)
    ax2.set_title(f"{title_prefix}直方图 (P={P}, R={R})", fontsize=14)
    ax2.set_xlabel('LBP编码值', fontsize=12)
    ax2.set_ylabel('频次', fontsize=12)
    ax2.grid(True, linestyle='--', alpha=0.3)
    # 设置坐标轴刻度向内
    ax2.tick_params(axis='both', direction='in', which='both')
    
    # 添加频次标签
    for bar, freq in zip(bars, hist):
        if freq > 0:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height + max(hist) * 0.01,
                    f'{freq}', ha='center', va='bottom', fontsize=8)
    
    plt.tight_layout()
    
    # 保存图像
    filename = os.path.join(OUTPUT_DIR, f"{title_prefix}_P{P}_R{R}.png")
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"已保存LBP图表到: {filename}")
    plt.close(fig)
    
    return lbp_image, hist

def generate_comprehensive_report(color_moments, glcm_features, lbp_stats):
    """生成综合特征分析报告"""
    report_file = os.path.join(OUTPUT_DIR, "地质特征分析报告.txt")
    
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write("隧道掌子面图像地质特征分析报告\n")
        f.write("=" * 50 + "\n\n")
        
        # 颜色矩分析
        f.write("一、颜色矩特征分析\n")
        f.write("-" * 30 + "\n")
        if color_moments:
            for channel, moments in color_moments.items():
                f.write(f"{channel}:\n")
                f.write(f"  均值: {moments['均值']:.3f}\n")
                f.write(f"  标准差: {moments['标准差']:.3f}\n")
                f.write(f"  偏度: {moments['偏度']:.3f}\n")
                f.write("\n")
        
        # GLCM特征分析
        f.write("二、灰度共生矩阵(GLCM)纹理特征分析\n")
        f.write("-" * 30 + "\n")
        if glcm_features:
            for feature_name, value in glcm_features.items():
                f.write(f"{feature_name}: {value:.6f}\n")
            f.write("\n")
            
            # 特征解释
            f.write("特征解释:\n")
            f.write("- 对比度: 反映图像的清晰度和纹理沟纹深浅程度\n")
            f.write("- 相关性: 反映图像灰度的线性依赖程度\n")
            f.write("- 能量: 反映图像灰度分布均匀程度和纹理粗细度\n")
            f.write("- 同质性: 反映图像纹理的局部变化程度\n\n")
        
        # LBP特征分析
        f.write("三、局部二值模式(LBP)纹理特征分析\n")
        f.write("-" * 30 + "\n")
        # 修复：使用 len() 检查而不是直接判断数组
        if lbp_stats is not None and len(lbp_stats) > 0:
            f.write(f"LBP模式总数: {len(lbp_stats)}\n")
            f.write(f"主要模式分布: {lbp_stats[:5] if len(lbp_stats) >= 5 else lbp_stats}\n")
            f.write("\nLBP特征可用于:\n")
            f.write("- 岩体表面纹理分析\n")
            f.write("- 节理裂隙模式识别\n")
            f.write("- 围岩风化程度评估\n")
    
    print(f"已生成综合分析报告: {report_file}")

# 主程序执行部分
if __name__ == "__main__":
    print(f"正在将可视化输出保存到: {OUTPUT_DIR}")
    print("=" * 60)

    # 1. GLCM演示
    print("\n1. 灰度共生矩阵(GLCM)特征提取与分析")
    print("-" * 40)
    
    # 创建示例图像块：4x4图像区域，灰度级0-3
    sample_patch_gray = np.array([
        [0, 0, 1, 1],
        [0, 0, 1, 1],
        [0, 2, 2, 2],
        [2, 2, 3, 3]
    ], dtype=np.uint8)

    # 计算不同方向的GLCM
    angles = [0, 45, 90, 135]
    all_glcm_features = {}
    
    for angle in angles:
        glcm_matrix = conceptual_glcm(sample_patch_gray, distance=1, angle_deg=angle, levels=4)
        features = calculate_glcm_features(glcm_matrix)
        all_glcm_features[f"{angle}度"] = features
        
        print(f"\n{angle}度方向GLCM矩阵:")
        print(glcm_matrix)
        print(f"纹理特征: {features}")
        
        plot_glcm(glcm_matrix, title=f"GLCM_{angle}度_距离1_级数4", features=features)

    # 2. 颜色矩演示
    print("\n\n2. 颜色矩特征提取与分析")
    print("-" * 40)
    
    # 创建多样化的彩色图像块用于更好的矩计算
    np.random.seed(42)
    varied_color_patch = np.random.randint(0, 256, size=(64, 64, 3), dtype=np.uint8)
    
    # 添加一些结构化的颜色区域模拟岩体特征
    varied_color_patch[0:32, 0:32] = [120, 100, 80]  # 模拟岩体颜色
    varied_color_patch[0:32, 32:64] = [140, 120, 100]  # 模拟不同岩性
    varied_color_patch[32:64, 0:32] = [100, 80, 60]   # 模拟风化区域

    color_moments_data = calculate_color_moments(varied_color_patch)

    if color_moments_data:
        print("\n颜色矩计算结果:")
        for channel, moments_val in color_moments_data.items():
            print(f"  {channel}: 均值={moments_val['均值']:.2f}, "
                  f"标准差={moments_val['标准差']:.2f}, 偏度={moments_val['偏度']:.2f}")
        plot_color_moments(color_moments_data, title="隧道掌子面颜色矩特征")
    else:
        print("无法计算示例图像块的颜色矩")

    # 3. LBP演示
    print("\n\n3. 局部二值模式(LBP)特征提取与分析")
    print("-" * 40)
    
    # 创建更复杂的灰度图像用于LBP分析
    lbp_input_patch = np.array([
        [10, 20, 30, 20, 15, 25, 35, 25],
        [50, 60, 70, 60, 55, 65, 75, 65],
        [90, 100, 110, 100, 95, 105, 115, 105],
        [130, 140, 150, 140, 135, 145, 155, 145],
        [20, 30, 40, 30, 25, 35, 45, 35],
        [60, 70, 80, 70, 65, 75, 85, 75],
        [100, 110, 120, 110, 105, 115, 125, 115],
        [140, 150, 160, 150, 145, 155, 165, 155]
    ], dtype=np.uint8)

    print(f"\nLBP输入图像块形状: {lbp_input_patch.shape}, 数据类型: {lbp_input_patch.dtype}")
    
    # 计算不同参数的LBP
    lbp_params = [(8, 1), (16, 2), (24, 3)]
    lbp_results = []
    
    for P, R in lbp_params:
        print(f"\n计算LBP特征 (P={P}, R={R})...")
        lbp_image, hist = calculate_and_plot_lbp(lbp_input_patch, P=P, R=R, 
                                               title_prefix=f"隧道掌子面LBP")
        lbp_results.append(hist)
        print(f"LBP直方图统计: 总模式数={len(hist)}, 最大频次={max(hist)}")

    # 4. 生成综合报告
    print("\n\n4. 生成综合特征分析报告")
    print("-" * 40)
    
    # 使用第一个角度的GLCM特征作为代表
    representative_glcm = all_glcm_features.get("0度", {})
    representative_lbp = lbp_results[0] if lbp_results else []
    
    generate_comprehensive_report(color_moments_data, representative_glcm, representative_lbp)

    print("\n" + "=" * 60)
    print("所有地质特征可视化和分析已完成！")
    print(f"请检查输出目录: {OUTPUT_DIR}")
    print("生成的文件包括:")
    print("- GLCM热力图和特征图表")
    print("- 颜色矩特征柱状图")
    print("- LBP图像和直方图")
    print("- 综合特征分析报告")
    print("=" * 60)
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")
    print("\n")